### ISSUE TITLE
how to play

### ISSUE THREAD

**Issue by aipymhx** [JiauZhang/DragGAN#1]

**Comment by JiauZhang** [comment]
```shell
python gui.py
```
But currently it is only the initial UI, and I am integrating it with the model.

**Comment by superggh** [comment]
only an image created

**Comment by TomerGamerTV** [comment]
> ```shell
> ```shell
> python gui.py
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> But currently it is only the initial UI, and I am integrating it with the model.
> ```

so it's currently non-functional?

**Comment by JiauZhang** [comment]
WIP

**Comment by TomerGamerTV** [comment]
> WIP

you should mention it in the readme or the description of this repo

**Comment by JiauZhang** [comment]
> > WIP
> 
> you should mention it in the readme or the description of this repo

Thanks for your suggestion. I have updated the README

**Comment by Zeqiang-Lai** [comment]
> > ```shell
> > ```shell
> > python gui.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But currently it is only the initial UI, and I am integrating it with the model.
> 
> so it's currently non-functional?

Feel free to use our workable implementation of DragGAN. https://github.com/Zeqiang-Lai/DragGAN

**Comment by JiauZhang** [comment]
it works…

**Comment by JiauZhang** [comment]
it works…
