### ISSUE TITLE
NOT work at all

### ISSUE THREAD

**Issue by ceval1987** [JiauZhang/DragGAN#13]
I cloned the repo and tried to use it, but it’s completely different from what was described in the paper. I cannot reproduce the results.  Why would an unfinished work be released?

**Comment by lorrding** [comment]
#1
It's literally written in the README file. It's a work in progress...

**Comment by ceval1987** [comment]
Thank you for your reply. I found a repo: https://github.com/Zeqiang-Lai/DragGAN, and it seems that the checkpoint can be used. Maybe you can plug the model into this GUI? I’m really looking forward to trying it!

**Comment by lorrding** [comment]
Also, in about a week or so the guys behind the original paperwork will release their code here https://github.com/XingangPan/DragGAN

**Comment by JiauZhang** [comment]
complete basic version.
