### ISSUE TITLE
GUI demo crashs when running on MacOS

### ISSUE THREAD

**Issue by zihaog0724** [JiauZhang/DragGAN#2]
Hi,

gui.py crashes at dpg.start_dearpygui() and throws a segmentation fault on MacOS. 
Any help will be appreciated. 

Thanks

**Comment by maevgor** [comment]
Hi! 
I was able to run the `gui.py` script with `dearpygui==1.9.0` on MacOS

**Comment by Kelier** [comment]
> Hi! I was able to run the `gui.py` script with `dearpygui==1.9.0` on MacOS

Could not find a version that satisfies the requirement dearpygui==1.9.0

**Comment by kamil-malinski** [comment]
> > Hi! I was able to run the `gui.py` script with `dearpygui==1.9.0` on MacOS
> 
> Could not find a version that satisfies the requirement dearpygui==1.9.0

try this: 

```console
pip install git+https://github.com/hoffstadt/DearPyGui@v1.9.1
```

**Comment by Kelier** [comment]
> > > Hi! I was able to run the `gui.py` script with `dearpygui==1.9.0` on MacOS
> > 
> > 
> > Could not find a version that satisfies the requirement dearpygui==1.9.0
> 
> try this:
> 
> ```
> pip install git+https://github.com/hoffstadt/DearPyGui@v1.9.1
> ```

python 3.9 fix it
