### ISSUE TITLE
The demo reports an error when running on MacOS

### ISSUE THREAD

**Issue by Nevermore1994** [JiauZhang/DragGAN#4]
Macbook Pro m1
macos:13.3.1
report error: AGX: Texture read/write assertion failed: bytes_per_row >= used_bytes_per_row

**Comment by Nevermore1994** [comment]
<img width="625" alt="image" src="https://github.com/JiauZhang/DragGAN/assets/14256650/604ffb9b-0104-4b00-9abb-2442c4d85748">
<img width="659" alt="image" src="https://github.com/JiauZhang/DragGAN/assets/14256650/1cdb7cab-0e4d-47f0-855b-3add45b26358">

**Comment by kamil-malinski** [comment]
I can confirm, I have the same issue

**Comment by JiauZhang** [comment]
https://github.com/JiauZhang/DragGAN/issues/2

**Comment by kamil-malinski** [comment]
this is not the same issue

**Comment by egorus1** [comment]
This project currently in progress, so probably after a while this problem will be solved.

**Comment by Zeqiang-Lai** [comment]
Feel free to use our workable implementation of DragGAN. https://github.com/Zeqiang-Lai/DragGAN

**Comment by Sovea** [comment]
@Nevermore1994 I already fix this error in #11, check this.

**Comment by Nevermore1994** [comment]
> @Nevermore1994 I already fix this error in #10, check this.

OK.thank you very much. @Sovea

**Comment by Sovea** [comment]
> > @Nevermore1994 I already fix this error in #10, check this.
> 
> OK.thank you very much. @Sovea

@Nevermore1994 In #10, I forgot to fix generate image and draw point on macOS, just did it in #11

**Comment by JiauZhang** [comment]
Hi @Nevermore1994, could help me to check whether it works well on MacOS? https://github.com/JiauZhang/DragGAN/pull/12
